### PR TITLE
Add readIlluminance() API to replace readLux()

### PR DESCRIPTION
**Pull request by sandeepmistry**
From the discussion in https://github.com/arduino-libraries/Arduino_MKRENV/pull/1#issuecomment-485841945.

cc/ @tigoe @simonepda @per1234 @cmaglie

### CODE REVIEW

**Comment by SimonePDA** [comment]
I am not sure if "brightness" is the right name of this measured value. It is the reading of the luminous flux that hits the sensor. If this flux is unfocused and from the environment it is the "ambient light" reading.

**Comment by sandeepmistry** [comment]
@SimonePDA thanks for the feedback, do you have a preferred API name then?

**Comment by SimonePDA** [comment]
Let's hear what the others have to say.

**Comment by tigoe** [comment]
Good point Simone. ReadLight? ReadLightSensor?  ReadLightLevel?

While we're at it, what are the SI units of UVA, B, and uvindex?

T

**Comment by SimonePDA** [comment]
As I added on the main lib page, the UVa and UVb vaue is the count of μW/cm2; this is stated on the datasheet. 

The UVIndex is an index, from 0 to 11+ with no specific unit. 

https://edit.arduino.cc/en/Reference/ArduinoMKRENV

**Comment by tigoe** [comment]
Good, thank you! I missed that detail.

t.

**Comment by sandeepmistry** [comment]
> Good point Simone. ReadLight? ReadLightSensor?  ReadLightLevel?

I'm ok with `readLightLevel()` or `readIlluminace()`. Let's see what @cmaglie thinks, as I discussed using `readBrightness()` with him yesterday.

**Comment by SimonePDA** [comment]
I chose to put all the values and their ranges in the main lib page. I think it gives a better picture of the shield performance/capabilities. The same table should go in the GS Page, now that we have agreed on what it is in it...

**Comment by tigoe** [comment]
Sounds good. That page seems to still be behind the edit password, which I
don't have. Let me know when you're done and ready for feedback.

t.

**Comment by cmaglie** [comment]
getIlluminace is as good as getBrightness, either one are fine IMHO

**Comment by sandeepmistry** [comment]
Ok, let's go with `readIlluminace()` then. I'll merge this now.

**Pull request merged**
